#!/usr/bin/env python
"""
This script was generated as part of a driver_script file by the
setup_testcases.py script.
"""
import sys
import os
import shutil
import glob
import subprocess
import argparse


# This script was generated by setup_testcases.py as part of a driver_script
# file.
os.environ['PYTHONUNBUFFERED'] = '1'
parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument("--no_base_mesh", dest="no_base_mesh",
                    help="If set, base_mesh case will not be run during "
                         "execution of this script.",
                    action="store_true")
parser.add_argument("--finalize_base_mesh", dest="finalize_base_mesh",
                    help="If set, base_mesh case will have symlinks replaced "
                         "with the files they point to, this occurs after any "
                         "case runs that have been requested.",
                    action="store_true")
parser.add_argument("--no_culled_mesh", dest="no_culled_mesh",
                    help="If set, culled_mesh case will not be run during "
                         "execution of this script.",
                    action="store_true")
parser.add_argument("--finalize_culled_mesh", dest="finalize_culled_mesh",
                    help="If set, culled_mesh case will have symlinks replaced "
                         "with the files they point to, this occurs after any "
                         "case runs that have been requested.",
                    action="store_true")

args = parser.parse_args()
base_path = os.getcwd()
dev_null = open('/dev/null', 'w')
error = False

if not args.no_base_mesh:
    os.chdir(base_path)
    os.chdir('base_mesh')

    print(" * Creating 2D global base mesh with jigsaw...")
    # Run command is:
    # ./run.py
    subprocess.check_call(['./run.py'], stdout=dev_null, stderr=None)
    print("     complete!  Created file:  base_mesh/base_mesh.nc")
if not args.no_culled_mesh:
    os.chdir(base_path)
    os.chdir('culled_mesh')

    print(" * Culling land cells from 2D global mesh...")
    # Run command is:
    # ./run.py
    subprocess.check_call(['./run.py'], stdout=dev_null, stderr=None)
    print("     complete!  Created file:  culled_mesh/culled_mesh.nc")
if error:
    sys.exit(1)
if args.finalize_base_mesh:
    old_dir = os.getcwd()
    os.chdir("base_mesh")
    file_list = glob.glob("*")
    for file in file_list:
        if os.path.islink(file):
            link_path = os.readlink(file)
            os.unlink(file)
            shutil.copyfile(link_path, file)
    os.chdir(old_dir)

if args.finalize_culled_mesh:
    old_dir = os.getcwd()
    os.chdir("culled_mesh")
    file_list = glob.glob("*")
    for file in file_list:
        if os.path.islink(file):
            link_path = os.readlink(file)
            os.unlink(file)
            shutil.copyfile(link_path, file)
    os.chdir(old_dir)

sys.exit(0)
